site_name: "Jvarkit"
repo_url: "https://github.com/lindenb/jvarkit"
repo_name: "GitHub"
docs_dir: docs

theme:
    name: readthedocs
    highlightjs: true
    html_show_sourcelink: false
    prev_next_buttons_location: both

nav:
        - "jvarkit" : JvarkitCentral.md
        - "addlinearindextobed" : AddLinearIndexToBed.md
        - "allelefreqcalc" : AlleleFrequencyCalculator.md
        - "backlocate" : BackLocate.md
        - "bam2haplotypes" : BamToHaplotypes.md
        - "bam2mnv" : BamToMNV.md
        - "bam2raster" : Bam2Raster.md
        - "bam2sql" : BamToSql.md
        - "bam2svg" : BamToSVG.md
        - "bam2wig" : Bam2Wig.md
        - "bam2xml" : Bam2Xml.md
        - "bamliftover" : BamLiftOver.md
        - "bammatrix" : BamMatrix.md
        - "bamphased01" : BamPhased01.md
        - "bamrenamechr" : ConvertBamChromosomes.md
        - "bamstats04" : BamStats04.md
        - "bamstats05" : BamStats05.md
        - "bamwithoutbai" : BamWithoutBai.md
        - "barcodegenerator" : BarcodeGenerator.md
        - "basecoverage" : BaseCoverage.md
        - "bedcluster" : BedCluster.md
        - "bedmergecnv" : BedMergeCnv.md
        - "bednonoverlappingset" : BedNonOverlappingSet.md
        - "bedremovebed" : BedRemoveBed.md
        - "bedrenamechr" : ConvertBedChromosomes.md
        - "bigwigmerge" : BigwigMerge.md
        - "bioalcidaejdk" : BioAlcidaeJdk.md
        - "biostar103303" : Biostar103303.md
        - "biostar105754" : Biostar105754.md
        - "biostar130456" : Biostar130456.md
        - "biostar139647" : Biostar139647.md
        - "biostar145820" : Biostar145820.md
        - "biostar154220" : Biostar154220.md
        - "biostar165777" : Biostar165777.md
        - "biostar170742" : Biostar170742.md
        - "biostar172515" : Biostar172515.md
        - "biostar173114" : Biostar173114.md
        - "biostar175929" : Biostar175929.md
        - "biostar178713" : Biostar178713.md
        - "biostar214299" : Biostar214299.md
        - "biostar234081" : Biostar234081.md
        - "biostar234230" : Biostar234230.md
        - "biostar251649" : Biostar251649.md
        - "biostar322664" : Biostar322664.md
        - "biostar332826" : Biostar332826.md
        - "biostar336589" : Biostar336589.md
        - "biostar352930" : Biostar352930.md
        - "biostar398854" : Biostar398854.md
        - "biostar404363" : Biostar404363.md
        - "biostar480685" : Biostar480685.md
        - "biostar489074" : Biostar489074.md
        - "biostar497922" : Biostar497922.md
        - "biostar59647" : Biostar59647.md
        - "biostar76892" : Biostar76892.md
        - "biostar77288" : Biostar77288.md
        - "biostar77828" : Biostar77828.md
        - "biostar78285" : Biostar78285.md
        - "biostar81455" : Biostar81455.md
        - "biostar84452" : Biostar84452.md
        - "biostar84786" : Biostar84786.md
        - "biostar86363" : Biostar86363.md
        - "biostar86480" : Biostar86480.md
        - "biostar90204" : Biostar90204.md
        - "biostar9462889" : Biostar9462889.md
        - "biostar9469733" : Biostar9469733.md
        - "biostar9501110" : Biostar9501110.md
        - "biostar9556602" : Biostar9556602.md
        - "biostar9566948" : Biostar9566948.md
        - "builddbsnp" : BuildDbsnp.md
        - "cnvtview" : CnvTView.md
        - "cnvvalidatorserver" : CNVValidatorServer.md
        - "convertliftoverchain" : ConvertLiftOverChain.md
        - "coveragematrix" : CoverageMatrix.md
        - "coverageplotter" : CoveragePlotter.md
        - "coverageserver" : CoverageServer.md
        - "evadumpfiles" : EVADumpFiles.md
        - "fastqshuffle" : FastqShuffle.md
        - "findallcoverageatposition" : FindAllCoverageAtPosition.md
        - "findavariation" : FindAVariation.md
        - "findgvcfsblocks" : FindGVCFsBlocks.md
        - "gff3upstreamorf" : Gff3UpstreamOrf.md
        - "goutils" : GoUtils.md
        - "groupbygene" : GroupByGene.md
        - "gtexrs2qtl" : GtexRsToQTL.md
        - "gtf2bed" : GtfToBed.md
        - "gtf2xml" : Gtf2Xml.md
        - "gtfliftover" : GtfLiftOver.md
        - "gtfretrocopy" : GtfRetroCopy.md
        - "htsfreemarker" : HtsFreemarker.md
        - "ibd2vcf" : IbdToVcf.md
        - "illuminadir" : IlluminaDirectory.md
        - "indexcov2vcf" : IndexCovToVcf.md
        - "kg2bed" : KnownGenesToBed.md
        - "kg2fa" : KnownGeneToFasta.md
        - "kg2gff" : KgToGff.md
        - "knownretrocopy" : KnownRetroCopy.md
        - "lowresbam2raster" : LowResBam2Raster.md
        - "mantamerger" : MantaMerger.md
        - "minicaller" : MiniCaller.md
        - "mkminibam" : MakeMiniBam.md
        - "msa2vcf" : MsaToVcf.md
        - "ncbitaxonomy2xml" : NcbiTaxonomyToXml.md
        - "ngsfilessummary" : NgsFilesSummary.md
        - "oboutils" : OboUtils.md
        - "optimizefisher" : OptimizeFisher.md
        - "plotsashimi" : PlotSashimi.md
        - "prettysam" : PrettySam.md
        - "pubmed404" : Pubmed404.md
        - "pubmedcodinglang" : PubmedCodingLanguages.md
        - "pubmeddump" : PubmedDump.md
        - "pubmedgender" : PubmedGender.md
        - "pubmedgraph" : PubmedGraph.md
        - "pubmedmap" : PubmedMap.md
        - "ref2html" : ReferenceToHtml.md
        - "repairfastq" : RepairFastq.md
        - "sam2json" : SamToJson.md
        - "sam2tsv" : Sam2Tsv.md
        - "sam4weblogo" : SAM4WebLogo.md
        - "samfindclippedregions" : SamFindClippedRegions.md
        - "samgrep" : SamGrep.md
        - "samjdk" : SamJdk.md
        - "samrmdupnames" : SamRemoveDuplicatedNames.md
        - "samviewwithmate" : SamViewWithMate.md
        - "scanlabguru" : ScanLabGuru.md
        - "scanretrocopy" : ScanRetroCopy.md
        - "setfiletools" : SetFileTools.md
        - "sortsamrefname" : SortSamRefName.md
        - "sortvcfoninfo" : SortVcfOnInfo.md
        - "splitvcf" : SplitVcf.md
        - "starretrocopy" : StarRetroCopy.md
        - "sv2fasta" : StructuralVariantToFasta.md
        - "sv2svg" : SvToSVG.md
        - "svcasescontrols" : SVCasesControls.md
        - "swingbamcov" : SwingBamCov.md
        - "swingbamview" : SwingBamView.md
        - "swingindexcov" : SwingIndexCov.md
        - "swingvcfjexl" : SwingVcfJexlFilter.md
        - "swingvcfview" : SwingVcfView.md
        - "texbam" : TextBam.md
        - "tssenrich" : TSSEnrichment.md
        - "ukbiobanksamples" : UKBiobankSelectSamples.md
        - "uniprot2svg" : UniprotToSvg.md
        - "vcf2bam" : VcfToBam.md
        - "vcf2intervals" : VcfToIntervals.md
        - "vcf2table" : VcfToTable.md
        - "vcf2xml" : Vcf2Xml.md
        - "vcfallelebalance" : VcfAlleleBalance.md
        - "vcfancestralalleles" : VcfAncestralAllele.md
        - "vcfbigbed" : VcfBigBed.md
        - "vcfbigwig" : VCFBigWig.md
        - "vcfburdenfisherh" : VcfBurdenFisherH.md
        - "vcfburdenmaf" : VcfBurdenMAF.md
        - "vcfburdenslidingwindow" : VcfBurdenSlidingWindow.md
        - "vcfcadd" : VcfCadd.md
        - "vcfcombinetwosnvs" : VCFCombineTwoSnvs.md
        - "vcfcomposite" : VCFComposite.md
        - "vcfconcat" : VcfConcat.md
        - "vcfdistancevariants" : VcfDistanceBetweenVariants.md
        - "vcffilterbyliftover" : VcfFilterByLiftOver.md
        - "vcffiltergenes" : VcFilterGenes.md
        - "vcffiltergtf" : VcfFilterGtf.md
        - "vcffilterjdk" : VcfFilterJdk.md
        - "vcffilterso" : VcfFilterSequenceOntology.md
        - "vcfflatten" : VCFFlatten.md
        - "vcfgatkeval" : VcfGatkEval.md
        - "vcfgenesplitter" : VcfGeneSplitter.md
        - "vcfgnomad" : VcfGnomad.md
        - "vcfgnomadsv" : VcfGnomadSV.md
        - "vcfgrantham" : VcfGrantham.md
        - "vcfgroupbypop" : VcfGroupByPopulation.md
        - "vcfhead" : VcfHead.md
        - "vcfmulti2one" : VcfMultiToOne.md
        - "vcfmulti2oneinfo" : VcfMultiToOneInfo.md
        - "vcfpar" : VcfPseudoAutosomalRegion.md
        - "vcfpeekaf" : VcfPeekAf.md
        - "vcfpeekvcf" : VcfPeekVcf.md
        - "vcfphased01" : VcfPhased01.md
        - "vcfpolyx" : VCFPolyX.md
        - "vcfrebase" : VcfRebase.md
        - "vcfregulomedb" : VcfRegulomeDB.md
        - "vcfrenamechr" : ConvertVcfChromosomes.md
        - "vcfscanupstreamorf" : VcfScanUpstreamOrf.md
        - "vcfserver" : VcfServer.md
        - "vcfsetdict" : VcfSetSequenceDictionary.md
        - "vcfshuffle" : VCFShuffle.md
        - "vcfspliceai" : VcfSpliceAI.md
        - "vcfsplitnvariants" : VcfSplitNVariants.md
        - "vcfspringfilter" : VcfSpringFilter.md
        - "vcfstats" : VcfStats.md
        - "vcfstrech2svg" : VcfStrechToSvg.md
        - "vcfsvannotator" : VCFSVAnnotator.md
        - "vcftail" : VcfTail.md
        - "vcftbi2bed" : VcfTbiToBed.md
        - "vcftrio" : VCFTrios.md
        - "wescnvsvg" : WesCnvSvg.md
        - "wgscoverageplotter" : WGSCoveragePlotter.md
        - "wib2bedgraph" : WibToBedGraph.md
        - "xsltstream" : XsltStream.md

